import type { Config } from 'tailwindcss';

/** Auto-generated from Stitch htmlCode tailwind-config — do not hand-edit colors. */
const config: Config = {
  "darkMode": "class",
  "content": [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/stitch-screens/**/*.{js,ts,jsx,tsx}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "on-tertiary": "#18343d",
        "primary-container": "#ff6b4a",
        "surface-bright": "#2e394d",
        "surface-container-lowest": "#030e20",
        "secondary-fixed-dim": "#ffba4b",
        "surface-tint": "#ffb4a3",
        "secondary-fixed": "#ffddb1",
        "on-primary": "#630f00",
        "on-secondary-container": "#5b3b00",
        "on-secondary": "#442b00",
        "surface-container-high": "#1f2a3d",
        "inverse-on-surface": "#253144",
        "surface-container": "#142032",
        "secondary-container": "#ea9f00",
        "tertiary-fixed-dim": "#afcbd7",
        "on-tertiary-fixed-variant": "#304b54",
        "surface": "#071325",
        "on-primary-fixed-variant": "#8c1900",
        "on-surface": "#d7e3fc",
        "surface-dim": "#071325",
        "inverse-primary": "#ae3115",
        "primary-fixed-dim": "#ffb4a3",
        "background": "#071325",
        "on-surface-variant": "#e1bfb8",
        "outline-variant": "#59413c",
        "surface-container-highest": "#2a3548",
        "outline": "#a88a83",
        "on-tertiary-container": "#1a353e",
        "on-tertiary-fixed": "#011f27",
        "tertiary-fixed": "#cae7f3",
        "on-error": "#690005",
        "secondary": {
          "DEFAULT": "#ffbd58",
          "foreground": "hsl(var(--secondary-foreground))"
        },
        "primary-fixed": "#ffdad2",
        "on-primary-container": "#661000",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#291800",
        "on-error-container": "#ffdad6",
        "on-background": "#d7e3fc",
        "surface-container-low": "#101c2e",
        "on-primary-fixed": "#3d0600",
        "inverse-surface": "#d7e3fc",
        "error-container": "#93000a",
        "primary": {
          "DEFAULT": "#ffb4a3",
          "foreground": "hsl(var(--primary-foreground))"
        },
        "tertiary-container": "#829ea9",
        "on-secondary-fixed-variant": "#624000",
        "tertiary": "#afcbd7",
        "surface-variant": "#2a3548",
        "border": "hsl(var(--border))",
        "input": "hsl(var(--input))",
        "ring": "hsl(var(--ring))",
        "foreground": "hsl(var(--foreground))",
        "card": {
          "DEFAULT": "hsl(var(--card))",
          "foreground": "hsl(var(--card-foreground))"
        },
        "destructive": {
          "DEFAULT": "hsl(var(--destructive))",
          "foreground": "hsl(var(--destructive-foreground))"
        },
        "muted": {
          "DEFAULT": "hsl(var(--muted))",
          "foreground": "hsl(var(--muted-foreground))"
        },
        "success": {
          "DEFAULT": "hsl(var(--success))",
          "foreground": "hsl(var(--success-foreground))"
        },
        "warning": {
          "DEFAULT": "hsl(var(--warning))",
          "foreground": "hsl(var(--warning-foreground))"
        }
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-padding": "1.5rem",
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
        "stack-md": "1rem",
        "gutter": "1rem"
      },
      "fontFamily": {
        "data-lg": [
          "JetBrains Mono"
        ],
        "headline-lg": [
          "Sora"
        ],
        "data-sm": [
          "JetBrains Mono"
        ],
        "headline-lg-mobile": [
          "Sora"
        ],
        "label-caps": [
          "JetBrains Mono"
        ],
        "display-lg": [
          "Sora"
        ],
        "body-md": [
          "Sora"
        ]
      },
      "fontSize": {
        "data-lg": [
          "18px",
          {
            "lineHeight": "24px",
            "fontWeight": "500"
          }
        ],
        "headline-lg": [
          "32px",
          {
            "lineHeight": "40px",
            "letterSpacing": "-0.01em",
            "fontWeight": "600"
          }
        ],
        "data-sm": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0.05em",
            "fontWeight": "400"
          }
        ],
        "headline-lg-mobile": [
          "24px",
          {
            "lineHeight": "32px",
            "fontWeight": "600"
          }
        ],
        "label-caps": [
          "10px",
          {
            "lineHeight": "12px",
            "letterSpacing": "0.1em",
            "fontWeight": "700"
          }
        ],
        "display-lg": [
          "48px",
          {
            "lineHeight": "56px",
            "letterSpacing": "-0.02em",
            "fontWeight": "700"
          }
        ],
        "body-md": [
          "16px",
          {
            "lineHeight": "24px",
            "fontWeight": "400"
          }
        ]
      },
      "boxShadow": {
        "brand-glow": "0 0 40px rgba(255, 107, 74, 0.15)"
      }
    }
  },
  "plugins": [],
  "safelist": [
    "!leading-tight",
    "!text-2xl",
    "!text-lg",
    "-translate-y-1/2",
    "Active:",
    "absolute",
    "aspect-video",
    "backdrop-blur-[16px]",
    "backdrop-blur-md",
    "backdrop-blur-sm",
    "backdrop-blur-xl",
    "badge-critical",
    "bg-[#FF6B4A]",
    "bg-[#FF6B4A]/40",
    "bg-[#FF6B4A]/50",
    "bg-[#FF6B4A]/70",
    "bg-[#FF6B4A]/80",
    "bg-[#FF6B4A]/90",
    "bg-[#FFB020]/20",
    "bg-[#FFB020]/30",
    "bg-[#FFB020]/40",
    "bg-[#FFB020]/50",
    "bg-[#FFB020]/60",
    "bg-[#FFB020]/70",
    "bg-[#FFB020]/80",
    "bg-black",
    "bg-black/40",
    "bg-emerald-400",
    "bg-emerald-500/10",
    "bg-error",
    "bg-error/10",
    "bg-gradient-to-br",
    "bg-gradient-to-r",
    "bg-gradient-to-tr",
    "bg-primary-container",
    "bg-primary-container/10",
    "bg-primary-container/20",
    "bg-primary-container/90",
    "bg-secondary",
    "bg-secondary-container",
    "bg-secondary-container/10",
    "bg-secondary-fixed/50",
    "bg-surface",
    "bg-surface-bright",
    "bg-surface-container",
    "bg-surface-container-high",
    "bg-surface-container-high/30",
    "bg-surface-container-highest",
    "bg-surface-container-highest/20",
    "bg-surface-container-highest/30",
    "bg-surface-container-highest/40",
    "bg-surface-container-highest/50",
    "bg-surface-container-lowest",
    "bg-surface-container/30",
    "bg-surface-container/40",
    "bg-surface-container/50",
    "bg-surface-container/80",
    "bg-surface/50",
    "bg-tertiary-container",
    "bg-tertiary-fixed-dim/30",
    "bg-tertiary-fixed-dim/40",
    "bg-tertiary-fixed-dim/5",
    "bg-tertiary/10",
    "bg-transparent",
    "bg-white",
    "bg-white/20",
    "bg-white/5",
    "blur-3xl",
    "blur-[120px]",
    "blur-[150px]",
    "border",
    "border-2",
    "border-b",
    "border-collapse",
    "border-dashed",
    "border-emerald-500/20",
    "border-l",
    "border-l-4",
    "border-l-secondary",
    "border-none",
    "border-primary",
    "border-primary-container",
    "border-primary-container/20",
    "border-r",
    "border-r-2",
    "border-secondary",
    "border-t",
    "border-t-[3px]",
    "border-t-primary-container",
    "border-white/10",
    "border-white/20",
    "border-white/5",
    "bottom-0",
    "bottom-[-20%]",
    "btn-primary",
    "col-span-1",
    "col-span-11",
    "col-span-12",
    "col-span-2",
    "cursor-crosshair",
    "cursor-pointer",
    "dark:bg-surface",
    "dark:hover:bg-surface-container-high",
    "dark:text-on-surface-variant",
    "dark:text-primary",
    "dark:text-primary-container",
    "docked",
    "drop-shadow-[0_2px_4px_rgba(255,107,74,0.5)]",
    "duration-200",
    "duration-500",
    "fixed",
    "flat",
    "flex",
    "flex-1",
    "flex-col",
    "flex-grow",
    "flex-shrink-0",
    "focus:border-primary-container/50",
    "focus:border-primary/50",
    "focus:outline-none",
    "focus:ring-1",
    "focus:ring-primary-container",
    "focus:ring-primary-container/50",
    "focus:ring-primary/50",
    "font-body-md",
    "font-bold",
    "font-data-lg",
    "font-data-sm",
    "font-display-lg",
    "font-headline-lg",
    "font-headline-lg-mobile",
    "font-label-caps",
    "font-medium",
    "font-semibold",
    "from-[#0a1628]",
    "from-primary-container",
    "from-primary/50",
    "from-secondary/50",
    "from-surface-container-highest",
    "full-width",
    "gap-1",
    "gap-2",
    "gap-3",
    "gap-4",
    "gap-6",
    "glass-panel",
    "grid",
    "grid-cols-1",
    "grid-cols-12",
    "grid-cols-2",
    "grid-cols-4",
    "grid-rows-6",
    "group",
    "group-hover:bg-error/20",
    "group-hover:bg-primary-container/20",
    "group-hover:bg-tertiary/20",
    "group-hover:opacity-100",
    "group-hover:text-white",
    "h-0.5",
    "h-1.5",
    "h-10",
    "h-14",
    "h-16",
    "h-2",
    "h-24",
    "h-3",
    "h-32",
    "h-48",
    "h-8",
    "h-9",
    "h-[50vw]",
    "h-[60vw]",
    "h-full",
    "h-screen",
    "hidden",
    "hover:bg-inverse-primary",
    "hover:bg-primary-container/10",
    "hover:bg-secondary-fixed/70",
    "hover:bg-surface-container",
    "hover:bg-surface-container-high",
    "hover:bg-surface-container-highest",
    "hover:bg-surface-container-low",
    "hover:bg-surface-container-low/50",
    "hover:bg-tertiary-fixed-dim/50",
    "hover:bg-tertiary-fixed-dim/60",
    "hover:bg-white/5",
    "hover:border-primary-container",
    "hover:border-primary-container/50",
    "hover:opacity-90",
    "hover:ring-1",
    "hover:ring-[#FF6B4A]",
    "hover:ring-[#FFB020]",
    "hover:ring-white",
    "hover:ring-white/50",
    "hover:scale-105",
    "hover:text-on-surface",
    "hover:text-primary",
    "hover:text-primary-container",
    "hover:text-secondary-fixed",
    "inline-flex",
    "inset-0",
    "items-baseline",
    "items-center",
    "items-end",
    "items-start",
    "justify-between",
    "justify-center",
    "justify-end",
    "leading-relaxed",
    "leading-tight",
    "left-0",
    "left-3",
    "left-[-10%]",
    "left-[25%]",
    "left-[60%]",
    "lg:block",
    "lg:col-span-3",
    "lg:col-span-4",
    "lg:col-span-8",
    "lg:col-span-9",
    "lg:grid-cols-12",
    "lg:p-8",
    "material-symbols-outlined",
    "max-h-32",
    "max-w-2xl",
    "max-w-[1600px]",
    "max-w-md",
    "mb-1",
    "mb-2",
    "mb-4",
    "mb-6",
    "mb-8",
    "mb-stack-lg",
    "md:flex",
    "md:grid-cols-2",
    "md:hidden",
    "md:ml-64",
    "md:pb-8",
    "md:text-2xl",
    "md:w-96",
    "min-h-[120px]",
    "min-h-[250px]",
    "min-h-[400px]",
    "min-h-screen",
    "min-w-0",
    "mix-blend-overlay",
    "ml-2",
    "ml-64",
    "mt-1",
    "mt-2",
    "mt-4",
    "mt-6",
    "mt-auto",
    "mx-auto",
    "no",
    "object-contain",
    "object-cover",
    "opacity-0",
    "opacity-20",
    "opacity-60",
    "opacity-70",
    "opacity-80",
    "overflow-hidden",
    "overflow-x-auto",
    "overflow-y-auto",
    "p-1",
    "p-2",
    "p-3",
    "p-4",
    "p-6",
    "p-container-padding",
    "pb-2",
    "pb-24",
    "pb-4",
    "pb-6",
    "pb-stack-lg",
    "pl-10",
    "pl-6",
    "pl-[8.333%]",
    "placeholder-on-surface-variant/50",
    "placeholder:text-on-surface-variant/50",
    "pointer-events-none",
    "pr-2",
    "pr-4",
    "pt-stack-md",
    "px-1",
    "px-1.5",
    "px-2",
    "px-3",
    "px-4",
    "px-5",
    "px-6",
    "px-container-padding",
    "py-0.5",
    "py-1",
    "py-1.5",
    "py-2",
    "py-3",
    "py-4",
    "py-6",
    "relative",
    "right-0",
    "right-[-10%]",
    "rounded",
    "rounded-DEFAULT",
    "rounded-full",
    "rounded-lg",
    "rounded-md",
    "rounded-sm",
    "rounded-t-sm",
    "rounded-xl",
    "row-span-4",
    "row-span-6",
    "scale-95",
    "shadow",
    "shadow-2xl",
    "shadow-[0_0_10px_rgba(255,107,74,0.2)]",
    "shadow-[0_0_10px_rgba(255,107,74,0.3)]",
    "shadow-[0_0_15px_rgba(255,107,74,0.3)]",
    "shadow-[0_0_15px_rgba(255,107,74,0.4)]",
    "shadow-[0_0_15px_rgba(255,107,74,0.5)]",
    "shadow-[0_0_15px_rgba(255,189,88,0.2)]",
    "shadow-[0_0_8px_#ff6b4a]",
    "shadow-[0_10px_30px_rgba(255,107,74,0.1)]",
    "shadow-[0_20px_40px_rgba(0,0,0,0.4)]",
    "shadow-sm",
    "shadows",
    "shrink-0",
    "sm:block",
    "sm:flex-row",
    "sm:hidden",
    "sm:items-end",
    "space-y-3",
    "sticky",
    "text-2xl",
    "text-[#4ade80]",
    "text-[10px]",
    "text-[12px]",
    "text-[14px]",
    "text-[16px]",
    "text-[18px]",
    "text-[20px]",
    "text-[32px]",
    "text-[9px]",
    "text-body-md",
    "text-center",
    "text-data-lg",
    "text-data-sm",
    "text-display-lg",
    "text-emerald-400",
    "text-error",
    "text-headline-lg",
    "text-headline-lg-mobile",
    "text-label-caps",
    "text-left",
    "text-lg",
    "text-on-primary-container",
    "text-on-surface",
    "text-on-surface-variant",
    "text-on-surface-variant/30",
    "text-on-surface-variant/50",
    "text-on-surface-variant/80",
    "text-on-tertiary-container",
    "text-primary",
    "text-primary-container",
    "text-right",
    "text-secondary",
    "text-secondary-container",
    "text-secondary-fixed",
    "text-sm",
    "text-tertiary",
    "text-white",
    "text-xl",
    "text-xs",
    "to-[#132f38]",
    "to-[#FF6B4A]",
    "to-inverse-primary",
    "to-secondary/50",
    "to-tertiary/50",
    "top-0",
    "top-1/2",
    "top-[-10%]",
    "tracking-wider",
    "tracking-widest",
    "transition-all",
    "transition-colors",
    "transition-opacity",
    "transition-transform",
    "truncate",
    "uppercase",
    "via-[#FFB020]",
    "w-1",
    "w-1.5",
    "w-1/3",
    "w-10",
    "w-12",
    "w-14",
    "w-16",
    "w-2",
    "w-24",
    "w-3",
    "w-32",
    "w-64",
    "w-8",
    "w-80",
    "w-9",
    "w-[12%]",
    "w-[50vw]",
    "w-[60vw]",
    "w-full",
    "xl:grid-cols-4",
    "z-0",
    "z-10",
    "z-40",
    "z-50"
  ]
};

export default config;
